cormacsblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import posts.views
import sitePages.views


#   allow display of images
from django.conf.urls.static import static  # allow us view images
from django.conf import settings            # retrieve values from the settings file

###########################################
#   for reading IMAGES Uploaded by users
###########################################
from django.views.static import serve
#from .settings import MEDIA_ROOT

urlpatterns = [
    url(r'^admin/', admin.site.urls),   # recommended to change URL from admin/ to sokething else
    url(r'^$', posts.views.index),
    url(r'^posts/',include('posts.urls')),
    url(r'^about/', sitePages.views.about, name="about"),
    #url(r'^media/(?P<path>.*)$',serve, {'document_root':MEDIA_ROOT}),# allows display of images
]#+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # allows display of images

posts/urls.py
from django.conf.urls import url
import views

# specific app URL pointable from template
app_name = 'posts'

urlpatterns = [
    url(r'^blog/$',views.post_list),
    url(r'^home/$', views.home, name="home"),
    url(r'^post_list/$', views.post_list, name="post_list"),
    url(r'^post_details/(?P<id>[0-9]+)/$', views.post_details, name="post_details"),
    url(r'^post_new/$',views.new_post, name='new_post'),
]

fileUpload/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

posts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
import django.utils.timezone


# Create your models here.
# title, date, picture, text
class Post(models.Model):
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to="media/images/", blank=True, null=True)       # need to install Pillow to use
    body = models.TextField()
    created_date = models.DateTimeField(default=django.utils.timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    # make title visible in admin instead of Post Object
    def __unicode__(self):
        return self.title

    #   make the pub_date more readable by providing a format
    #   can be called directly from the template
    def pub_date_pretty(self):
        return self.published_date.strftime('%b %d %Y')

    def summary(self):
        return self.body[:100]

sitePages/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

posts/forms.py
from django import forms
from .models import Post


class BlogPostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title','body','image')

fileUpload/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

posts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from .models import Post

from .forms import BlogPostForm
from django.shortcuts import redirect

import logging
logger = logging.getLogger(__name__)



def index(request):
    return render(request, 'posts/index.html')


def home(request):
    #   retrieve all posts and REVEERSE ORDDERED by date
    posts = Post.objects.order_by('-published_date')
    args = {'posts': posts}
    return render(request, 'posts/home.html', args)


def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    args = {'posts': posts}
    return render(request, 'posts/post_listing.html', args)


def post_details(request,post_id):
    post = get_object_or_404(Post,pk=post_id)
    #post = Post.objects.get(pk=post_id)
    return render(request, 'posts/post_details.html', {'post': post})


def new_post(request):
    """
    If the view was accessed because the Submit button was clicked, then it
    will be true that the request.method == POST
    """
    if request.method=="POST":
        logger.debug('contents of request.FILES is ')
        logger.debug(request.FILES)
        #logger.debug('contents of request.body is ')
        #logger.debug( request.body)

        #   retrieve the values from teh submitted form
        form = BlogPostForm(request.POST, request.FILES)
        #   check if valid
        if form.is_valid():
            #   stop the form from saving to DB just yet
            #   but save it as an instance of Post model
            #   Hold off on saving until extra values have been added to the Post model (LOGIC HOOK)
            post = form.save(commit=False)
            #   then retrieve values to add to the model
            post.author = request.user  #   must be logged in (even in admin) for this value to exist
            post.published_date = timezone.now()
            #   save to the model
            post.save()
            #   Redirect user to post_details
            logger.debug('post.pk is ')
            logger.debug(post.pk)
            #return redirect(post_details,post.pk)
            return HttpResponse('post uploaded')
    else:
        form = BlogPostForm()
    return render(request,'posts/blog_posts_form.html',{'form':form})

sitePages/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.


def about(request):
    return render(request, 'sitePages/about.html')


def index(request):
    return render(request, 'posts/index.html')

posts/templates/posts/blog_posts_form.html
{% extends 'base.html' %}
{% block content %}
    {% load bootstrap_tags %}
    <h1>New Post</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form | as_bootstrap }}
        <button type="submit" class="btn btn-info">Save</button>
    </form>
{% endblock %}

posts/templates/posts/home.html
{% extends 'base.html' %}
{% block content %}
    {% load staticfiles %}
    <h2>Latest Blog</h2>
    {% for post in posts.all %}
        <h3><a href="{% url 'posts:post_details' post.id %}"><h3>{{ post.title }}</h3></a></h3>
        <p><h4><i class="fa fa-clock-o" aria-hidden="true"></i> {{ post.pub_date_pretty }}</h4></p>
        <p><img src="{{ post.image.url }}"  class="img-fluid center-block img-thumbnail" style="max-height:300px;"></p>
        <p>{{ post.summary }}...(click to view more)</p>
        <hr>
    {% endfor %}
{% endblock %}px;

posts/templates/posts/index.html
{% extends 'base.html' %}
{% block content %}
    {% load static %}
    <h1>Index Page</h1>
    <p><a href="{% url 'posts:home' %}">Home is where the heart is</a></p>
    <p><img src="{% static 'images/profile_cormac.png' %}"></p>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block content %}
    <h1>Post Detail</h1>
    <p>{{ post.title }}</p>
    <p>{{ post.pub_date_pretty }}</p>
    <p><img src="{{ post.image.url }}" class="img-fluid center-block img-thumbnail" style="max-height:150px;"></p>
    <p>{{ post.body }}</p>
    <p><a href="{% url 'posts:home' %}">Home</a></p>
    <div id="disqus_thread"></div>
    <script>
        //  UNIQUELY IDENTIFY COMMENTS TO THIS ENTERTAINER OBJ
        var disqus_config = function () {
          this.page.identifier = 'post-{{ post.id }}'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
            console.log('PAGE_IDENTIFIER');
            console.log(PAGE_IDENTIFIER);
        };
        (function() { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        s.src = 'https://cormacsblog.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
{% endblock %}

posts/templates/posts/post_details.html
{% extends 'base.html' %}
{% block content %}
    {% load staticfiles %}
    <h1>Post Detail</h1>
    <p>{{ post.title }}</p>
    <p>{{ post.pub_date_pretty }}</p>
    {% if post.image %}
        <p><img src="/media/{{ post.image }}"></p>
    {% endif %}
    <p>{{ post.body|linebreaks }}</p>
    <p><a href="{% url 'posts:post_list' %}">Home</a></p>
    <p><button class="btn btn-default" onclick="location.href='/posts/post_list/'">Back to Blog</button></p>
    <div id="disqus_thread"></div>
    <script>
        //  UNIQUELY IDENTIFY COMMENTS TO THIS ENTERTAINER OBJ
        var disqus_config = function () {
          this.page.identifier = 'post-{{ post.id }}'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
            console.log('PAGE_IDENTIFIER');
            console.log(PAGE_IDENTIFIER);
        };
        (function() { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        s.src = 'https://cormacsblog.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
{% endblock %}

posts/templates/posts/post_listing.html
{% extends 'base.html' %}
{% block content %}
    {% load staticfiles %}
    <div class="row">
        <div class="col-sm-6">
            <h2>Latest Blogs</h2>
        </div>
        <div class="col-sm-6">
            <a href="/posts/post_new/">***Click Here To Create New Post***</a>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <hr>
        </div>
    </div>
    {% for post in posts.all %}
        <div class="row">
            <div class="col-sm-12">
                <div class="row">
                    <div class="col-sm-12">
                        <h3><a href="{% url 'posts:post_details' post.id %}"><h3>{{ post.title }}</h3></a></h3>
                    </div>
                </div>
            </div>
            <div class="col-sm-12">
                <div class="row">
                    <div class="col-md-2 col-sm-3 text-center">
                        <a class="story-img" href="#">
                            <!--<img src="http://placehold.it/100" style="width:100px; height:100px; background-color: #12ABB2; color: #ffffff#" class="img-circle">-->
                            {% if post.image %}
                                <p><img src="{{ post.image.url }}"  style="width:100px; height:100px; background-color: #12ABB2; color: #ffffff" class=" img-fluid center-block img-thumbnail"></p> <!--class="img-fluid center-block img-thumbnail" style="max-height:300px;"></p>-->
                            {% endif %}
                        </a>
                    </div>
                    <div class="col-md-10 col-sm-9">
                        <div class="row">
                            <div class="col-xs-9">
                                <p>{{ post.body|truncatewords:30 }}</p>
                                <p>{{ post.summary }}...</p>
                                <p><a href="/posts/post_details/{{ post.id }}">(click to view more)</a></p>
                                <p>{{ post.pub_date_pretty }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <hr>
            </div>
        </div>

    {% endfor %}
{% endblock %}

sitePages/templates/sitePages/about.html
{% extends 'base.html' %}
{% block content %}
    <h1>THIS IS THE ABOUT PAGE</h1>
{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/blog.css' %}">
    <script src="https://use.fontawesome.com/1038c1131d.js"></script>
    </head>
<body>
    <!-- Just an image -->

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                   <!-- <li class="nav-item active">
                        <a class="nav-link" href="{% url 'posts:home' %}">Home <span class="sr-only">(current)</span></a>
                    </li>-->
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'posts:post_list' %}">Posts</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'about' %}">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="http://www.twitter.com/nickchuckwalter">Twitter</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#">Disabled</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <div id="masthead">
            <div class="row">
                <h1>stack
                    <p id="logo" class="lead">Cormac's Blog</p>
                </h1>
            </div>
        </div>
        {% block content %}
        {% endblock %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

</body>
</html>